### PR TITLE
Paste "Standard CI workflow" from r-lib/actions/v2-branch

### PR DESCRIPTION
**Pull request by howardbaek**
Copy and pasted this workflow: https://github.com/r-lib/actions/tree/v2-branch/examples#standard-ci-workflow 

This came from a Posit community answer: https://community.rstudio.com/t/r-cmd-check-ubuntu-20-04-fails-missing-rcmdcheck/131519/2

### CODE REVIEW

**Comment by howardbaek** [comment]
@cansavvy  I am sure why I'm seeing all these test failure errors. Maybe the [Standard CI workflow](https://github.com/r-lib/actions/tree/v2-branch/examples#standard-ci-workflow) is not the right one to use?

**Comment by cansavvy** [comment]
Have you read the errors that are listed under Details? Might just take a bit of sleuthing. I can dig into this a bit more or we can pair code on it tomorrow if that would be helpful.

**Comment by cansavvy** [comment]
And yeah the reason a lot of them are failing is related to #18

**Comment by howardbaek** [comment]
Yeah we can look at this tomorrow.

**Comment by howardbaek** [comment]
@cansavvy I'm not sure why I keep on getting  `Error: Error: object '***' not found` from GHA. I've tried few different things to input the API keys inside `options()`, but I keep on getting the same error message. 

Can you please have a look?

**Comment by cansavvy** [comment]
> @cansavvy I'm not sure why I keep on getting  `Error: object '***' not found` from GHA. I've tried few different things to input the API keys inside `options()`, but I keep on getting the same error message. 
> 
> 
> 
> Can you please have a look? 

Ah I actually know why. Put quotes around the GitHub secret calls in the Rscript call. I'll put a code suggestion to show.

**Comment by howardbaek** [comment]
@cansavvy All the R-CMD-checks are successful 🥳

**Review by cansavvy — APPROVED** [review]
This looks great to me! Great job working on this! We can close #18 ! :tada: 

Next stop: 1) getting this to work from ari. 2) Also probably republishing this in CRAN

**Pull request merged**
